This is the static blog/website of kwlin.github.io.

* The master branch contains all the static (web)files (*.html, *.css etc.) generated by Jekyll
* The source branch contains all the source (like Markdown, templates etc.) files to generate the static files.

There is continuous integration build configured in Travis CI for generating the static file when there is a change in the source branch. The jekyll result will be published to the master branch.
 